version: "3.7"
services:
  postgres:
    image: postgres:13.4
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
      POSTGRES_INIT_DB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d